### ISSUE TITLE
No longer working in latest fusion update

### ISSUE THREAD

**Issue by hyperboras** [FlorianPommerening/FingerJoints#20]
Heya,

Love this plugin but it no longer works with latest fusion 360 update. any ideas?

**Comment by BlomsD** [comment]
glad to see this because I am having the same problem. The add-in doesn't open a box to do anything

**Comment by FlorianPommerening** [comment]
I just tried running the plugin in the latest Fusion version (2.0.15050). It worked without issues for me. Can you tell me more about your cases?
* What Fusion versions are you running on?
* On what operating system?
* Did you try to reinstall the plugin?
* Does the button to create finger joints show up in the "Modify" menu?
* If the button shows up, what happens when you click on it, i.e., does the dialog open, can you select the pieces you want to join, ...?
* Do you see any error message?

**Comment by bringert** [comment]
It works for me too (Fusion 360 2.0.15050 x86_64 [Rosetta 2], macOS 13.1 (22C65) on Mac14,2) . But it was a bit confusing at first since the README says to click Run in the Add-ins dialog, which doesn't exist (anymore?), but doesn't say to look under Solid > Modify (where it is now).

So I guess a small update to the README would help.

**Comment by FlorianPommerening** [comment]
Thanks, I'll try to improve the README.

**Comment by Mateusz-Szczepaniak** [comment]
It still work ? Im new in fusion 360 and I dont know how tu use it :) where is icon to use this addon ?

**Comment by FlorianPommerening** [comment]
Did you follow the instructions in the Readme to install the plugin? Once it is installed, a button should show up in the "Modify" menu (see my message above).
