### ISSUE TITLE
Feature Requests: Blind Box Joint and CNC dog bones

### ISSUE THREAD

**Issue by infieldbounteous** [FlorianPommerening/FingerJoints#24]
Amazing script!! Nice work!
I am using _finger joints_ to model a cabinet then going back and making it full blind, then adding dogones so I can cut it in one pass on a CNC machine.
 

1. add an option for dog bone corners 
2. add an option for full-blind 
 

![full_blind_box_joint](https://github.com/FlorianPommerening/FingerJoints/assets/91095434/b8a56106-6a82-4584-9a86-ea66fd73bd30)

<img width="1083" alt="Screenshot 2023-07-01 at 11 00 01 PM" src="https://github.com/FlorianPommerening/FingerJoints/assets/91095434/e5765f21-2a98-4b31-ae31-f91e97fb7358">
<img width="1054" alt="Screenshot 2023-07-01 at 10 59 54 PM" src="https://github.com/FlorianPommerening/FingerJoints/assets/91095434/41d9f626-23d8-4285-a0e9-38f07d11c17d">
<img width="909" alt="Screenshot 2023-07-01 at 10 59 46 PM" src="https://github.com/FlorianPommerening/FingerJoints/assets/91095434/5ded696c-3c2e-446a-8718-e545eca0d425">

**Comment by FlorianPommerening** [comment]
There is a separate plugin for dogbone joints (https://github.com/DVE2000/Dogbone/). I don't plan to integrate this functionality because it doesn't fit the design of the plugin well. My plugin does not require parts to be at right angles to each other (or be rectangular, for that matter), so there is no notion of the "edge" where the two parts meet.

As for the full blind joint, isn't this what you would get naturally, if you don't fully overlap the parts but have one part be slightly larger then the other before creating the joint?

**Comment by FlorianPommerening** [comment]
I'll close this because both features are incompatible with the plugin. They only work for two rectangular parts meeting at a right angle. Sorry I don't have better news but I don't see how this is possible based on the current code.

**Comment by infieldbounteous** [comment]
Hi Florian, yes, I’m using the dog one plug-in now.  It is great. You are right by being creative with how the bodies overlap I can get very close to a double-blind joint.

Thanks for a great add-on!!

Outlook<https://aka.ms/qtex0l> for iOS
________________________________
