### ISSUE TITLE
re: " gap between the fingers and notches"

### ISSUE THREAD

**Issue by getgray** [FlorianPommerening/FingerJoints#6]
This plugin is great!  One issue though.  The "gap" that you added between the notches in necessary when you CNC cut the corners, so, as you know, the notches will fit.  If the notches are the same size, the interference fit that would create is a problem.  
The adjustable gap is just what is needed....

BUT, like the interference between tabs and holes, you need a gap at the bottom of a notch as well.  For the same reason.  Without that gap the tab can't quite go deep enough into the notch.  The perfect fit depth will in practice cause the panel to sit "proud" of the interfacing tabs.  Need the notches depth to either have the same gap, or better, a separately sized depth gap.  Screenshot of extreme gap example showing place where gap is also needed:
![image](https://user-images.githubusercontent.com/20461271/128250553-ab7af100-7371-4cf9-a521-954d15e78e4b.png)

**Comment by FlorianPommerening** [comment]
Adding this is not straightforward due to the way the computation is currently done (there is no assumption that the pieces are rectangular or meet at a right angle, so even finding this edge is tricky). I have an idea that could lead to a gap at this position but it might mess up more complex cases. I could add it as a "use-at-your-own-risk" option but it will be a while before I get around to trying this.

For future reference: the hacky solution I'm thinking about is to scale up the slices before the join operation. They would get bigger in all directions, including the direction overlapping the work piece. All other directions shouldn't matter if the pieces overlap at a right angle and meet at their edges (for a lap joint this would also extend into the gap.) Maybe I can also scale them only in directions perpendicular to the join axis, so they don't interfere with the gap.

**Comment by getgray** [comment]
I understand.  Thank you.  A workaround for me it to lie when I make the model and set the material thicker by "the gap".  I *think* that would accomplish the same thing.  In my image and in that case, the bottom sides of the interlocking tabs will all be shorter than I said they were by just that amount.  Now, that could cause issues if I had other interfacing components unrelated to the joint (with the wrong size stock), but probably not a big deal for my usage.  Maybe using that idea would help your solution..

**Comment by FlorianPommerening** [comment]
I managed to find some time to implement the hacky solution I mentioned above (released as v1.2). There is an additional complication that I didn't see before: it is not possible to identify the direction that goes "into" the part. During the computation the z axis goes along the joint and the x and y axes are perpendicular to it but not necessarily aligned with the parts (the parts might not even have a straight edge to align to). This means, I cannot scale up the tool body only in the direction of the part to cut out a larger chunk. My solution for now is to scale up in all directions with the same factor. Unless the axes just happen to go in the right direction this will lead to incorrect gap sizes. If the intersection of the two parts is not a square, it also means that one side will have a larger gap than the other.

I think the clean solution for this would be to compute an offset around the tool body, but I don't know how to do this with bRepBodies. I'll close this issue with the temporary fix in v1.2 and will open a new issue to look for a more permanent solution.
